### PR TITLE
Add zengetter to IMobSpawnerBaseLogic

### PR DESCRIPTION
**Pull request by democat3457**
Uses access transformer to assist
Also upgrades to 2847 (Still FG2)

### CODE REVIEW

**Comment by jaredlll08** [comment]
Could that obfuscation helper be turned into an access transformer instead?

**Comment by democat3457** [comment]
Huh, I was not aware that was a thing. Will do.

**Comment by kindlich** [comment]
Also, since you're adding something to an existing class, please use `default` methods, or an Expansion class.

**Comment by democat3457** [comment]
Done.

**Review by kindlich — APPROVED** [review]
Looks fine to me

@jaredlll08 
Does an update in the used forge version need a new patch-version?
Like going from `4.1.20` to `4.1.21` ?

**Comment by jaredlll08** [comment]
> Looks fine to me
> 
> @jaredlll08
> Does an update in the used forge version need a new patch-version?
> Like going from `4.1.20` to `4.1.21` ?

Nope, to be honest unless something super major comes up, I think we are stuck on 4.1.20.x for a long time

**Pull request merged**
