### PR TITLE
Add MCEntity.hasTag method.

### PR DESCRIPTION
**Pull request by Hydrogen897**
Add hasTag method.
Return Type: boolean
Need Type: String

Just a simply function.
But it is very useful.
:)

### CODE REVIEW

**Comment by Hydrogen897** [comment]
Method example:
```Java
import crafttweaker.api.entity.MCEntity;

entities.hasTag("age");
//return true or false
```

**Comment by jaredlll08** [comment]
Your code doesn't compile, you can't have a static local field.

Also you code could be as simple as:
```java
    @ZenCodeType.Method
    public static boolean hasTag(Entity internal, String tag) {
        return internal.getTags().contains(tag);
    }
```

Saying that, is there an issue with doing:
```zenscript
var entity = somehowGetEntity();
var result = "age" in entity.getTags();
//return true or false
```

**Comment by Hydrogen897** [comment]
> Your code doesn't compile, you can't have a static local field.
> 
> Also you code could be as simple as:
> 
> ```java
>     @ZenCodeType.Method
>     public static boolean hasTag(Entity internal, String tag) {
>         return internal.getTags().contains(tag);
>     }
> ```
> 
> Saying that, is there an issue with doing:
> 
> ```zenscript
> var entity = somehowGetEntity();
> var result = "age" in entity.getTags();
> //return true or false
> ```

thanks for pointing out error.
I changed it.

**Comment by Hydrogen897** [comment]
then `in` cant use in scripts.

**Comment by Kasualix** [comment]
Can't merge? Really need this feature in my modpack.

**Comment by jaredlll08** [comment]
Sorry I should have mentioned, the actual bug is that the scripting engine doesn't know about the `Set` class, I would rather fix the issue at that level (telling it about the `Set` class) instead of this once off specific fix.

**Comment by jaredlll08** [comment]
Sorry this took so long, you should be able to use `"name" in tags` now.

it is currently only fixed in 1.20.1, but I'll propagate the changes down to 1.16

**Pull request closed without merging**
