### PR TITLE
Refactor brewing

### PR DESCRIPTION
**Pull request by friendlyhj**

### CODE REVIEW

**Comment by jaredlll08** [comment]
I do not want to change where LATE_ACTIONS are ran. They run where they do so that JEI can run after them and it ensures that everything is up to date.

**Comment by friendlyhj** [comment]
JEI scans all recipes on load complete, but CrT always runs before JEI. So it is fine.
The author of the issue is my friend, his problem is a mod registeres its brewing recipes on postInit. So CrT can't tweak them.

**Comment by jaredlll08** [comment]
I remember putting it where I did for a reason, I unfortunately don't remember the reason.

I'm super uncomfortable changing it now, I would much prefer just having *another* list that get processed in load complete, and leaving everything that uses this list be.

**Comment by friendlyhj** [comment]
I don't understand why still retain actions that have already been applied. We can't reload or undo actions in 1.12. They are not used anymore. Keeping them is just a waste of memory.

**Comment by jaredlll08** [comment]
I think there was some miscommunication. 
I'm all for clearing the list, I was more saying that the stuff that currently uses the LAST_ACTIONS list shouldn't be changed in terms of when it is loaded.

What you've done here:
https://github.com/CraftTweaker/CraftTweaker/pull/1305/commits/dfcb315e5f2249669ecca5d50dd7778f5a48e8ba
Looks perfectly fine to me

**Comment by friendlyhj** [comment]
So are there any problems now? Could be merged?

**Review by jaredlll08 — APPROVED** [review]

**Pull request merged**
