### PR TITLE
fix: missing count data while casting IIngredientWithAmount to IData

### PR DESCRIPTION
**Pull request by friendlyhj**
This is only a small patch. Maybe it can't work properly in *advanced* ingredients (`IngredientList`, `IngredientVanillaPlus`). But I had tested that it works in `MCItemStack` and `MCTag<Item>`

### CODE REVIEW

**Comment by kindlich** [comment]
The reason why we didn't add IData casters to IngredientWithAmount and TagWithAmount is that Vanilla Ingredient _does not support_ amount data.
Therefore Serializers would need to parse and put that field in themselves if they wanted to use something like amount.

Since this can go multiple ways, we decided against adding it.
A few possible examples:
```
{
    "ingredient": <ingredientWithoutAmount>,
    "count": 3
}
```

```
{
    "count": 3,
    <other properties of the ingredient>
}
```

Then the question: `amount` vs. `count`, or maybe other words exist for that as well.

**Comment by friendlyhj** [comment]
No, it supports count data
In this script, we used count data. And it works well

Or I should make only MCItemStack and Item Tag can be cast to IData.

https://paste.ubuntu.com/p/FFQVfrK5Sb/

**Comment by kindlich** [comment]
As I said, that's up to their serializer:
<https://github.com/SilentChaos512/Silents-Mechanisms/blob/1.16.x/src/main/java/net/silentchaos512/mechanisms/crafting/recipe/AlloySmeltingRecipe.java#L116>

**Comment by friendlyhj** [comment]
ok, you are right. But item ingredient still can use `count` data, by using NBTIngredient of Forge. We can use it for recipe output.

**Comment by jaredlll08** [comment]
You can't use NbtIngredient with everything, since it is going to mess with stack matching, if you check the history, I added those lines specifically to fix vanilla stack matching.

As kindlich said, by default, in vanilla, Ingredients don't have a count/amount, and there are hundreds of different ways that mods could implement that in their json, this is why I advocate for mods to have actual support compared to having to use `addJSONRecipe`.

**Comment by friendlyhj** [comment]
fair enough.

**Pull request closed without merging**
