### PR TITLE
Catch user inputs for mob drops that would result in an empty stack. …

### PR DESCRIPTION
**Pull request by The-Arcanian**
…And provide more useful errors.

Fixes https://github.com/CraftTweaker/CraftTweaker/issues/573.

### CODE REVIEW

**Comment by jaredlll08** [comment]
After further inspection... @The-Arcanian 

You aren't taking into account that this method has Optional params, meaning they are defaulted to 0

https://github.com/CraftTweaker/CraftTweaker/blob/5bac656a6df399bbe7216e99ce8553bc8296d90e/CraftTweaker2-API/src/main/java/crafttweaker/api/entity/IEntityDefinition.java#L28

So I reverted the PR (I only caught this when I loaded my world and saw the error)

**Comment by kindlich** [comment]
You could change `@Optional int` to `@Optional(valueLong = 1) int` or whatever value should be defaulted, for float it would be valueDouble

**Comment by The-Arcanian** [comment]
@kindlich It is an int.
This was my first PR so how do I do this. After I fix it, do I tack it on to this PR somehow, or do I need to make a new PR? Because as shown in the issue I referenced, jared has no intention of fixing this bug...

**Comment by kindlich** [comment]
You'd need to do a new PR since this one was already merged (otherwise your new commits would've simply been appended)

I know that it is an int, but you'll have to use valueLong as byte, int, short, long will all use that field to get their default value from.

I advise we'd take this over to jared's discord as it's a little more active over there.
discord.blamjared.com

**Comment by jaredlll08** [comment]
It isn't a bug, the underlying issue is that itemstacks cannot have a stack size of 0 (aka empty). ANYWHERE, not in a recipe and not as a drop. this is only "fixing" one "problem", you are just going to come back next week with a PR that makes it check in Crafting table recipes if the inputs are empty. 

Week after that you are going to come back with another one for Furnace recipes, there are too many places where an IITemStack is asked for, and we can't catch them all, so instead, we throw an error when trying to create an empty IItemStack, that is the ONLY solution that covers all of the uses of IItemStack.

**Comment by The-Arcanian** [comment]
Yes, because I want to have a recipe that uses or gives an item stack of 0. Don't be obtuse. Mob drops are different because the base game using ranges that can be less than one. Because the mod can't, it is up to the mod to anticipate this use case (especially because no documentation is given to the contrary) and provide a useful error, not crash the game. (How many times do I have to repeat this before it sinks in?)
Your statements are amounting to: "Something in the code is causing a crash, but it's not a bug." Just stop, you're embarrassing yourself. If there is something in the code that causes a crash, it is by definition a bug. The bug is not your fault, these things happen, nor does it have to be fixed immediately. But ignoring it is just willful ignorance.

**Comment by jaredlll08** [comment]
It. Is. Not. A. Bug.

It is a crash that WE throw, intentionally, because the argument given is not a valid argument!

https://github.com/CraftTweaker/CraftTweaker/blob/1.12/CraftTweaker2-MC1120-Main/src/main/java/crafttweaker/mc1120/item/MCItemStack.java#L55

Fixing it would be removing that line, which would introduce a heap of other errors, quite literally breaking everything, don't believe me? You have a fork, remove that line, load up the game, tell me how it goes :)

**Pull request merged**
