### PR TITLE
Fix anyDamage doesn't work for some items (IC2 etc.)

### PR DESCRIPTION
**Pull request by friendlyhj**

### CODE REVIEW

**Comment by jaredlll08** [comment]
yea uh, I am not happy using the field itself, some mods use NBT for damage and ignore the field (immersive engineering for example).

What is the issue with IC2?

**Comment by friendlyhj** [comment]
EnigmaticaModpacks/Enigmatica2Expert#2055
The items of IC2 use both the damage field and NBT for damage. The `setDamage` method is overriden, changed to rely on the NBT, causing us to not be able to call the setter to modifiy the damage.
`<ic2:xxx>.anyDamage()` can't return an item with damage wildcard. Then `<ic2:xxx>.anyDamage().matches(ic2:xxx:26>)` returns false. Since damage checking is always before NBT, even though we ignore the nbt checking, the different damage still make the two items fail to match.

**Comment by jaredlll08** [comment]
I am still worried that this may break support for other mods, especially those that have a valid `setItemDamage` implementation.

**Comment by friendlyhj** [comment]
In old CraftTweaker, the `withTag` and `anyDamage` implementations are calling the construtor of `ItemStack` (item, count, damage parameters) and setting NBT to the ItemStack then. The implementation doesn't cause the issue, but it can't retain forge capability nbt. So I changed in  https://github.com/CraftTweaker/CraftTweaker/pull/1550/commits/331d9d4d493dee2022b3130c09252f9705398496 to copy and apply modification.

I have a compromise solution. Since `anyDamage` is always used for recipe matching, and capability NBT is ignored in recipes, there is no need to keep capability NBT. I plan to rollback my changes to `anyDamage` to fix the issue.

**Pull request merged**
