### PR TITLE
basic dispenser behavior support

### PR DESCRIPTION
**Pull request by friendlyhj**
I haven't tested it yet. So mark it draft first.

### CODE REVIEW

**Comment by jaredlll08** [comment]
One concern is that I don't know when mods add dispense behaviors, so we may need to delay the actions?

**Comment by friendlyhj** [comment]
ready for review again.

**Review by jaredlll08 — APPROVED** [review]
Has this been tested yet?

**Comment by friendlyhj** [comment]
Tested. Everything is fine.

**Comment by friendlyhj** [comment]
Did you forget to merge it?

**Comment by jaredlll08** [comment]
Nope, wanted to make sure it was test first, and I never got a notification that you replied until now

**Pull request merged**
