### PR TITLE
Change the chat logger to only affect players who have op permission

### PR DESCRIPTION
**Pull request by ghost**
A personal feature request from me, not sure if you like the idea or want to implement it, but:

This should make it so that only op's get msgs in game about errors in any ct/zs scripts being run - regular players don't need this and if they end up needing it they can check crafttweaker.log

An alternative to this method that gives both old and new option would be to make a config option check to activate op-only chat messages or not.

### CODE REVIEW

**Comment by jaredlll08** [comment]
Not interested, sorry but as we've always said, fix the issues.


Also have some patience, I know your issue is relating to recipe stages, I will look at it when I have time.

**Comment by ghost** [comment]
With or without the issue I'm having I think in modpacks players shouldn't be burdened with dealing with error messages unnecessarily but ops and players directed to the ct logs should be, I think it'd be a useful change - all good though sir 👍

**Comment by jaredlll08** [comment]
> players shouldn't be burdened with dealing with error messages unnecessarily

You're right, ***players*** shouldn't have to be burdened with error messages, which is why we tell people (modpack authors) to fix the errors in the first place.

Also the way you've implemented means only people in creative mode and that are OP can see the errors, not all OPs.

**Comment by ghost** [comment]
Fair enough sir 💯

**Pull request closed without merging**
