### PR TITLE
Change IItemStack#createEntityItem to float

### PR DESCRIPTION
**Pull request by democat3457**

### CODE REVIEW

**Comment by democat3457** [comment]
this shouldn't break backwards-compatibility, right @jaredlll08?

otherwise, it's ready for review

**Comment by jaredlll08** [comment]
Wouldn't this break backwards compat with things that implement IItemStack?

**Comment by democat3457** [comment]
Oh I was thinking of methods that called `super.createEntityItem` but still, mods probably shouldn't be overriding that anyway?

**Comment by jaredlll08** [comment]
https://github.com/CraftTweaker/ContentTweaker/blob/develop/1.12/src/main/java/com/teamacronymcoders/contenttweaker/api/ctobjects/mutableitemstack/IMutableItemStack.java#L11

ContentTweaker does.

You should be able to just make a new method that accepts a float instead of an int?

**Comment by friendlyhj** [comment]
The implementation class extends `MCItemStack`, https://github.com/CraftTweaker/ContentTweaker/blob/c1c3df9af665351de4afaada91315bad9078bb71/src/main/java/com/teamacronymcoders/contenttweaker/api/ctobjects/mutableitemstack/MCMutableItemStack.java#L8
So I don't think it will break CoT.

**Comment by jaredlll08** [comment]
I was more so using ContentTweaker as an example, there may be other mods that do implement IItemstack directly

**Review by friendlyhj — CHANGES_REQUESTED** [review]
You forgot to change it
https://github.com/CraftTweaker/CraftTweaker/blob/1.12/CraftTweaker2-API/src/main/java/crafttweaker/api/item/ItemStackUnknown.java

**Comment by democat3457** [comment]
> You forgot to change it
> https://github.com/CraftTweaker/CraftTweaker/blob/1.12/CraftTweaker2-API/src/main/java/crafttweaker/api/item/ItemStackUnknown.java

what again is ItemStackUnknown used for (yes i'll make the changes after school, or just add a new method overload)

**Comment by jaredlll08** [comment]
What is the status of this?

**Comment by democat3457** [comment]
will update

**Comment by democat3457** [comment]
ready for re-review @jaredlll08

**Pull request merged**
