### PR TITLE
Block Hardness and LeftClickBlock Event

### PR DESCRIPTION
**Pull request by friendlyhj**

### CODE REVIEW

**Comment by friendlyhj** [comment]
ready for review

**Comment by jaredlll08** [comment]
Has the hardness stuff been tested?

**Comment by friendlyhj** [comment]
Yes, it works well.

**Comment by jaredlll08** [comment]
So I am slightly worried that there will be a mismatch between the Block's hardness (which is a field in it's properties field) and the BlockState's hardness, but I guess mods shouldn't really be using the Block's hardness value anyway, so I'll merge now and deal with the mismatch at a later point

**Pull request merged**
